networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: meetingapp-app
    env_file:
      - .env
    ports:
      - "8888:8000"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"