networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  redis-data:

services:
  db:
    image: mongo:8
    container_name: meetingapp-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - app-network
    volumes:
      - db-data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    depends_on:
      - db
      - redis
    container_name: meetingapp-app
    env_file:
      - .env
    ports:
      - "8888:8000"
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  redis:
    image: redis:latest
    container_name: meetingapp-redis
    command:
      - /bin/sh
      - -c
      # https://stackoverflow.com/a/72593084
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}"
    networks:
      - app-network
    volumes:
      - redis-data:/var/lib/redis/data
      - ./redis_data/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
